#!/bin/bash
echo 'NUKING ALL GODDAMN DOCKER IMAGES AND CONTAINERS'
echo 'HIDE YO KIDS, HIDE YO WIFE'
echo '
                                    xxxxxxx
                               x xxxxxxxxxxxxx x
                            x     xxxxxxxxxxx     x
                                   xxxxxxxxx
                         x          xxxxxxx          x
                                     xxxxx
                        x             xxx             x
                                       x
                       xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxx
                        xxxxxxxxxxxxx     xxxxxxxxxxxxx
                         xxxxxxxxxxx       xxxxxxxxxxx
                          xxxxxxxxx         xxxxxxxxx
                            xxxxxx           xxxxxx
                              xxx             xxx
                                  x         x
                                       x'
docker rm -vf $(docker ps -a -q)  && docker rmi -f $(docker images -a -q)
